

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author oscar
 */
public class Programa extends javax.swing.JFrame {

    /**
     * Creates new form Programa
     */
    public Programa() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TextNombre = new javax.swing.JTextField();
        TextApellidos = new javax.swing.JTextField();
        TextTelefono = new javax.swing.JTextField();
        BtVentasP = new javax.swing.JButton();
        TextTelefono1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        TextNombre1 = new javax.swing.JTextField();
        TextApellidos1 = new javax.swing.JTextField();
        BtRegistrar1 = new javax.swing.JButton();
        BtReportesP = new javax.swing.JButton();
        BtRegistrar3 = new javax.swing.JButton();
        BtRegistrarP = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setMinimumSize(new java.awt.Dimension(1050, 620));
        jPanel3.setPreferredSize(new java.awt.Dimension(1050, 620));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1_VnJ1MGwCkkQ5umi895C6Fg 1.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 610));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Ellipse 28.png"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Orange.png"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Buscar cliente");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, 350, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Complete la informacion de sus clientes");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Nombres * ");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Apellidos *");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 350, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Telefono *");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("Correo electronico * ");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 170, -1, -1));

        TextNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TextNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNombreActionPerformed(evt);
            }
        });
        jPanel3.add(TextNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 380, 230, 30));

        TextApellidos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TextApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextApellidosActionPerformed(evt);
            }
        });
        jPanel3.add(TextApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 380, 230, 30));

        TextTelefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TextTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextTelefonoActionPerformed(evt);
            }
        });
        jPanel3.add(TextTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 200, 230, 30));

        BtVentasP.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        BtVentasP.setText("Ventas");
        BtVentasP.setBorder(null);
        BtVentasP.setBorderPainted(false);
        BtVentasP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtVentasPMouseClicked(evt);
            }
        });
        BtVentasP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtVentasPActionPerformed(evt);
            }
        });
        jPanel3.add(BtVentasP, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 530, 150, 40));

        TextTelefono1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TextTelefono1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextTelefono1ActionPerformed(evt);
            }
        });
        jPanel3.add(TextTelefono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, 230, 30));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Registro de clientes");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 350, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setText("Nombres * ");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, -1, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setText("Apellidos *");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 90, -1, -1));

        TextNombre1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TextNombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNombre1ActionPerformed(evt);
            }
        });
        jPanel3.add(TextNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 230, 30));

        TextApellidos1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TextApellidos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextApellidos1ActionPerformed(evt);
            }
        });
        jPanel3.add(TextApellidos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 120, 230, 30));

        BtRegistrar1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        BtRegistrar1.setText("Registrar");
        BtRegistrar1.setBorder(null);
        BtRegistrar1.setBorderPainted(false);
        BtRegistrar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtRegistrar1MouseClicked(evt);
            }
        });
        jPanel3.add(BtRegistrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, 150, 40));

        BtReportesP.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        BtReportesP.setText("Reportes");
        BtReportesP.setBorder(null);
        BtReportesP.setBorderPainted(false);
        BtReportesP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtReportesPMouseClicked(evt);
            }
        });
        BtReportesP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtReportesPActionPerformed(evt);
            }
        });
        jPanel3.add(BtReportesP, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 530, 150, 40));

        BtRegistrar3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        BtRegistrar3.setText("Buscar cliente");
        BtRegistrar3.setBorder(null);
        BtRegistrar3.setBorderPainted(false);
        BtRegistrar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtRegistrar3ActionPerformed(evt);
            }
        });
        jPanel3.add(BtRegistrar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 440, 150, 40));

        BtRegistrarP.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        BtRegistrarP.setText("Registrar");
        BtRegistrarP.setBorder(null);
        BtRegistrarP.setBorderPainted(false);
        BtRegistrarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtRegistrarPActionPerformed(evt);
            }
        });
        jPanel3.add(BtRegistrarP, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 530, 150, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNombreActionPerformed

    private void TextApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextApellidosActionPerformed

    private void TextTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextTelefonoActionPerformed

    private void TextTelefono1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextTelefono1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextTelefono1ActionPerformed

    private void TextNombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNombre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNombre1ActionPerformed

    private void TextApellidos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextApellidos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextApellidos1ActionPerformed

    private void BtVentasPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtVentasPActionPerformed

       
        
    }//GEN-LAST:event_BtVentasPActionPerformed

    private void BtReportesPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtReportesPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtReportesPActionPerformed

    private void BtRegistrar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtRegistrar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtRegistrar3ActionPerformed

    private void BtRegistrarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtRegistrarPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtRegistrarPActionPerformed

    private void BtRegistrar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtRegistrar1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BtRegistrar1MouseClicked

    private void BtReportesPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtReportesPMouseClicked
        Reportes reportes = new Reportes();
        reportes.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtReportesPMouseClicked

    private void BtVentasPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtVentasPMouseClicked
        Ventas ventas = new Ventas();
        ventas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtVentasPMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Programa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtRegistrar1;
    private javax.swing.JButton BtRegistrar3;
    private javax.swing.JButton BtRegistrarP;
    private javax.swing.JButton BtReportesP;
    private javax.swing.JButton BtVentasP;
    private javax.swing.JTextField TextApellidos;
    private javax.swing.JTextField TextApellidos1;
    private javax.swing.JTextField TextNombre;
    private javax.swing.JTextField TextNombre1;
    private javax.swing.JTextField TextTelefono;
    private javax.swing.JTextField TextTelefono1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
